POST http://localhost:9000/invitaciones/rsvp/626700ca824e02836c43b569 HTTP/1.1
Content-Type: application/json

{
    "rsvp":0
}


# POST https://bodabackend.herokuapp.com/invitaciones/rsvp/626700ca824e02836c43b569 HTTP/1.1

# {
#     "rsvp":1
# }
# Content-Type: application/json

